apimServiceName: pkapimwksp-prod
namedValues:
  - name: TimeNow
    displayName: TimeNow
    value: "Test"
loggers:
    - name: pkapimwksp-ai
      loggerType: applicationInsights
      description: App Insights for APIM
      resourceId: "/subscriptions/fe5f965f-9f7f-4846-a2c7-957be7ad6de1/resourceGroups/pkapimwksp-prod-rg/providers/microsoft.insights/components/pkapimwksp-prod-ai"
      credentials:
        instrumentationKey: "{{Logger-Credentials--62a894a946346109e82820b1}}" 
      isBuffered: true
    - name: eventhublogger
      loggerType: azureEventHub
      description: Event Hub Logger
      resourceId: "/subscriptions/fe5f965f-9f7f-4846-a2c7-957be7ad6de1/resourceGroups/pkapimwksp-prod-rg/providers/Microsoft.EventHub/namespaces/pkapimwksp-prod-eh"
      credentials:
        name: "apim-prod-eh"
        connectionString: "{{Logger-Credentials--62a8acfa46346109e82820bb}}" 
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Verbose
     loggerId: "/subscriptions/fe5f965f-9f7f-4846-a2c7-957be7ad6de1/resourceGroups/pkapimwksp-prod-rg/providers/Microsoft.ApiManagement/service/pkapimwksp-prod/loggers/pkapimwksp-prod-ai"       
